name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'models/**'
      - 'requirements.txt'
      - '.github/workflows/deploy_api.yml'
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v4
      with:
        app-name: 'fastapi-cityscape-unet'
        slot-name: 'Production'
