name: Deploy Streamlit to Azure

on:
  push:
    paths:
      - 'webapp/**'
      - 'requirements.txt'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload Streamlit appp to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_STREAMLIT_APP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_STREAMLIT_PUBLISH_PROFILE }}
          package: .
